### ISSUE TITLE
Resampling over large gaps in data

### ISSUE THREAD

**Issue by TorSy** [databrickslabs/tempo#265] opened 2022-10-13 06:26 UTC
Question:
I have a large dataset (1000 GB + ) worth of JSON data that is IoT sensor data. In order to regularize time-series to a set sampling frequency I use tempo. 
One issue I experience is that the sensor data can have gaps in it. Sometimes months worth of missing data. The interpolate function fills all this in, which is really not what I want, as this interpolated data is not based on anything substantial. It should be left as Null or NA.

Could a parameter "interpolation limit" or similar be implemented? Currently I have a very computationally expensive workaround to this problem.

**Comment by tnixon** [comment] 2022-10-17 20:17
Hi @TorSy - thanks for your feedback. We plan to separate out the interpolation and resampling functions in a future update so that you should be able to upsample and just fill with "default" values (nulls, zeros or empty strings). The interpolation function would be separate and could be chained together with resampling if that's the desired effect, but not necessary if not.

**Comment by nuno-s** [comment] 2023-04-13 11:02
Hi, I have a small question about how the resampling and interpolation works.

For example:
- My data has 4 different sensors
- I want my data with a frequency of 1 second. 
- 1 sensor have a timestamp value like: since 2000-01-1 until 2000-12-1 (frequency 2 seconds) 
- Other 3 sensors has dates since 2023-01-01 until now. (frequency 3 seconds) 

Questions:
-The resample will create data since 2000-12-1 until now, within a interval of 1 second? Even if the max of sensor 1 is only the end of 2000?. If so, what happens to that data?
- The resampling should work only inside the time frame of the partition columns? if my partition column is the sensor id, the resampling and interpolation, should only work for that time interval. for example, for sensor 1, should only interpolate data since 2000-01-1 until 2000-12-1, and for the sensor, 2,3 and 4, 2023-01-01 until the last timestamp.

This is correct?

But the timestamp has a few records with dates from a few records with 


 I have several sensors (different ids) that have a value, 

but the timestamp is like from 1990 to 2022. This means that the resample will creat

**Comment by epa095** [comment] 2023-11-15 08:47
@TorSy Sounds like https://github.com/databrickslabs/tempo/issues/147 no?

**Comment by tnixon** [comment] 2023-11-16 18:54
Agreed @epa095 - I think this is a duplicate of #147.

**Closed by tnixon** 2023-11-16 18:54 UTC
Labels: enhancement, future
